apiVersion: v1
kind: Service
metadata:
  name: mycaddy-caddy-ingress-controller
  namespace: caddy-service
  labels:
    helm.sh/chart: caddy-ingress-controller-1.1.0
    app.kubernetes.io/name: caddy-ingress-controller
    app.kubernetes.io/instance: mycaddy
    app.kubernetes.io/version: "v0.2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: "LoadBalancer"
  loadBalancerIP:  #Deprecated in Kubernetes v1.24
  externalTrafficPolicy: 
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: caddy-ingress-controller
    app.kubernetes.io/instance: mycaddy