apiVersion: v1
kind: ServiceAccount
metadata:
  name: caddy-ingress-controller
  namespace: caddy-service
  labels:
    helm.sh/chart: caddy-ingress-controller-1.1.0
    app.kubernetes.io/name: caddy-ingress-controller
    app.kubernetes.io/instance: mycaddy
    app.kubernetes.io/version: "v0.2.1"
    app.kubernetes.io/managed-by: Helm